### ISSUE TITLE
False positives: Requirement 5 - Authentication and Authorization of Application Resources

### ISSUE THREAD

**Issue by UREURE** [atlassian-labs/connect-security-req-tester#50]
**Describe the bug**
Te tests results says that "_One or more endpoints returned a <400 status code without authentication information. This may indicate that your app is not performing authentication and authorization checks_".

Example 1:

- https://pfc-develop.cloud.deiser.com/page/project_navigator-view
- Res Code: 200
- Req Method: GET
- Auth Header: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiI3YzM0NWI5MjAyMWU5NGEyMDNkNTc4MzIwZGE5MDI5Yzc2OTY0OWJhNDUzYzMyNWE4N2Q5MjZiZDE4NTdjOWZhIiwiaXNzIjoiY3NydC1mYWtlLXRva2VuLWlnbm9yZSIsImV4cCI6MTYxOTA5ODUxNCwiaWF0IjoxNjE5MDg3NzE0fQ.cDTr3q3330neIu7sUVKEXvsL5FDoJmrMl2wlBEGsfDU

If we use Postman to do that request, we have 401 in the response.

Example 2:

- https://pfc-develop.cloud.deiser.com/webhooks/projects/updated/test
- Res Code: 200
- Req Method: GET
- Auth Header: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiI3YThmNGJjOTZiZDEzNjM5MmRhYjFmNjA1YWZhMDI0ZDgxNzQ1OTUwOWEwNzM3OTY3MjdjNGQ2NWQyYTU4YjQwIiwiaXNzIjoiY3NydC1mYWtlLXRva2VuLWlnbm9yZSIsImV4cCI6MTYxOTA5ODUxNCwiaWF0IjoxNjE5MDg3NzE0fQ.tmw6xQNosMUT47PNqkJcOtRUuihsXP2_OK8l6s0B2Jw

If we use Postman to do that request, we have 405 in the response.

**To Reproduce**
Run tests to https://profields-cloud.deiser.com/atlassian-connect.json using:

`docker run -v $(pwd)/out:/app/out connect-security-req-tester https://profields-cloud.deiser.com/atlassian-connect.json`

**Expected behavior**
Pass Requirement 5 tests.

**Comment by seanmarpo** [comment]
Hi there,
When reproducing those two examples, I do indeed get a 200 response code. I'm including the cURL commands below to verify.

### Example 1
`curl https://pfc-develop.cloud.deiser.com/page/project_navigator-view -H 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiI3YzM0NWI5MjAyMWU5NGEyMDNkNTc4MzIwZGE5MDI5Yzc2OTY0OWJhNDUzYzMyNWE4N2Q5MjZiZDE4NTdjOWZhIiwiaXNzIjoiY3NydC1mYWtlLXRva2VuLWlnbm9yZSIsImV4cCI6MTYxOTA5ODUxNCwiaWF0IjoxNjE5MDg3NzE0fQ.cDTr3q3330neIu7sUVKEXvsL5FDoJmrMl2wlBEGsfDU'
-vv`

### Example 2
`curl https://pfc-develop.cloud.deiser.com/webhooks/projects/updated/test -H 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiI3YThmNGJjOTZiZDEzNjM5MmRhYjFmNjA1YWZhMDI0ZDgxNzQ1OTUwOWEwNzM3OTY3MjdjNGQ2NWQyYTU4YjQwIiwiaXNzIjoiY3NydC1mYWtlLXRva2VuLWlnbm9yZSIsImV4cCI6MTYxOTA5ODUxNCwiaWF0IjoxNjE5MDg3NzE0fQ.tmw6xQNosMUT47PNqkJcOtRUuihsXP2_OK8l6s0B2Jw' -vv`

This seems to be working as intended, but let me know if you feel otherwise.

**Comment by UREURE** [comment]
We have fixed the error.
This issue can be closed.
Thank you @seanmarpo!
